### ISSUE TITLE
python2 or python3

### ISSUE THREAD

**Issue by bletvaska** [tiborradacovsky/gk2itgeeks#3]
what version of python are you using? because if python3, then syntax of some examples is for python2 (for example example for input, import).

**Comment by sakonn** [comment]
Python 2.7.12

**Comment by bletvaska** [comment]
and may i ask what is the reason? it is bad practice to start with something, what is no longer supported. especially with the basics.

**Comment by tiborradacovsky** [comment]
Python 3.5+
